In [25]:
import re
import pandas as pd
import nflreadpy as nfl



pbp = nfl.load_pbp([i for i in range(1999, 2025)])

In [26]:

cols = [
    "play_id", 
    "drive_play_id_ended", 
    "drive_play_id_started", 
    "game_id", 
    "season", #lo mas probable es que esto no se use
    "temp", 
    "weather", 
    "wind",
    "drive_game_clock_start", 
    "drive_quarter_start", 
    "drive_start_transition", #ayuda a saber como acabo el drive anterior
    #del otro equipo
    "drive_start_yard_line", 
    "series", 
    "posteam", #para saber que equipo tiene el balon
    "defteam", 
    #marcadores
    "posteam_score", 
    "defteam_score", 
    "score_differential", 
    "qtr", 
    "time", #tiempo relativo del cuarto lo mismo que quarter_seconds_remaining
    "down", #en que down estuvieron
    "yardline_100", #yardas faltantes para la zona de anotacion
    "ydstogo", #yardas pero para el primer down
    "extra_point_attempt", 
    "extra_point_result", 
    "return_touchdown", #si anoto el equipo que no estaba atacando
    "touchdown", #binaria que indica si hubo touchdown
    "td_team",  #que equipo anoto
    "safety", #creo que es cuando los capturan en su zona
    "two_point_attempt", #ambas binarias
    "two_point_conv_result",
    "fumble", 
    "fumble_forced", 
    "fumble_not_forced", 
    "fumble_lost", 
    "fumble_out_of_bounds", 
    "fumble_recovery_1_yards", #yardas recorridas desde el punto donde
    #se recupero el balon
    "fumble_recovery_1_team",
    "run_gap", 
    "run_location", 
    "rush_attempt", 
    "rush_touchdown", 
    "rushing_yards", 
    # === castigos ===
    "penalty", 
    "penalty_team", 
    "penalty_type", 
    "penalty_yards", 
    # === primer down ==
    "first_down_pass", 
    "first_down_penalty", 
    "first_down_rush", 
    # aqui es si no hicieron ni gol ni patada
    "third_down_converted",
    "third_down_failed",
    "fourth_down_converted",
    "fourth_down_failed", 
    #
    "defteam_score_post", 
    "posteam_score_post",
    "score_differential_post", 
    "sp", #si la jugada fue anotadora
    #pases
    "air_yards",  #incluye el caso de pases incompletos, ademas
    #si hay pases que esten antes de la linea donde empezo la jugada
    #el numero sera negativo. Si quieres solo la maginutd val abs
    "complete_pass", 
    "incomplete_pass", 
    "interception", 
    "pass_attempt", 
    "pass_location", 
    "pass_touchdown", 
    "receiving_yards", #las yardas del receptor para poder agarrarlo
    "yards_after_catch",
    "passing_yards", #yardas totales en el aire y tambien yardas 
    #que corrio el jugador despues de agarrar hasta que acabo la jugada, 
    #i.e. yards_after_catch
    "sack", #si capturaron al QB
    # === patadas ===
    "field_goal_attempt", 
    "field_goal_result", #categorico
    "kick_distance", 
    "kickoff_attempt", 
    "kickoff_downed", 
    "kickoff_fair_catch", #si fue recepcion libre
    "kickoff_in_endzone", #si llego a la zona de anotacion
    "kickoff_out_of_bounds", 
    "punt_attempt", #patada de despeje
    "punt_blocked", 
    "punt_downed", 
    "punt_fair_catch", #recepcion libre
    "punt_in_endzone", 
    "punt_out_of_bounds", 
    "return_team", 
    "return_yards", #son las que avanza un jugador después de recibir el balón del equipo contrario
    # === jugadas en general ===
    "play",
    "first_down",  #si se logro el first down
    "out_of_bounds", #si se salieron del campo
    "yards_gained", 
    "qb_scramble", 
    "series_result", 
    "series_success", #si se llego a primer down
    "play_type",
    # === tackleadas ===
    "solo_tackle", 
    #assist_tackle = 1 y tackle_with_assist = 1
    #tackle_with_assist_1_player_name = T.Bernard (el principal)
    #assist_tackle_1_player_name = Ta.Johnson (el que ayudó)
    "tackle_with_assist", 
    "assist_tackle", 
    # === drives ===
    "drive_end_yard_line", 
    "drive_ended_with_score", 
    #===reslutados===
    "away_score", 
    "home_score", 
    "result", 
    "total"
]

pbp[cols]

shape: (1_230_857, 102)
┌─────────┬─────────────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────┬───────┐
│ play_id ┆ drive_play_ ┆ drive_play_ ┆ game_id     ┆ … ┆ away_score ┆ home_score ┆ result ┆ total │
│ ---     ┆ id_ended    ┆ id_started  ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---    ┆ ---   │
│ f64     ┆ ---         ┆ ---         ┆ str         ┆   ┆ i32        ┆ i32        ┆ i32    ┆ i32   │
│         ┆ f64         ┆ f64         ┆             ┆   ┆            ┆            ┆        ┆       │
╞═════════╪═════════════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════╪═══════╡
│ 35.0    ┆ 150.0       ┆ 35.0        ┆ 1999_01_ARI ┆ … ┆ 25         ┆ 24         ┆ -1     ┆ 49    │
│         ┆             ┆             ┆ _PHI        ┆   ┆            ┆            ┆        ┆       │
│ 60.0    ┆ 150.0       ┆ 35.0        ┆ 1999_01_ARI ┆ … ┆ 25         ┆ 24         ┆ -1     ┆ 49    │
│         ┆             ┆             ┆ _PHI        ┆   ┆            ┆            ┆        ┆       │
│ 82.0    ┆ 150.0       ┆ 35.0        ┆ 1999_01_ARI ┆ … ┆ 25         ┆ 24         ┆ -1     ┆ 49    │
│         ┆             ┆             ┆ _PHI        ┆   ┆            ┆            ┆        ┆       │
│ 103.0   ┆ 150.0       ┆ 35.0        ┆ 1999_01_ARI ┆ … ┆ 25         ┆ 24         ┆ -1     ┆ 49    │
│         ┆             ┆             ┆ _PHI        ┆   ┆            ┆            ┆        ┆       │
│ 126.0   ┆ 150.0       ┆ 35.0        ┆ 1999_01_ARI ┆ … ┆ 25         ┆ 24         ┆ -1     ┆ 49    │
│         ┆             ┆             ┆ _PHI        ┆   ┆            ┆            ┆        ┆       │
│ …       ┆ …           ┆ …           ┆ …           ┆ … ┆ …          ┆ …          ┆ …      ┆ …     │
│ 4158.0  ┆ 4247.0      ┆ 4158.0      ┆ 2024_22_KC_ ┆ … ┆ 22         ┆ 40         ┆ 18     ┆ 62    │
│         ┆             ┆             ┆ PHI         ┆   ┆            ┆            ┆        ┆       │
│ 4181.0  ┆ 4247.0      ┆ 4158.0      ┆ 2024_22_KC_ ┆ … ┆ 22         ┆ 40         ┆ 18     ┆ 62    │
│         ┆             ┆             ┆ PHI         ┆   ┆            ┆            ┆        ┆       │
│ 4203.0  ┆ 4247.0      ┆ 4158.0      ┆ 2024_22_KC_ ┆ … ┆ 22         ┆ 40         ┆ 18     ┆ 62    │
│         ┆             ┆             ┆ PHI         ┆   ┆            ┆            ┆        ┆       │
│ 4225.0  ┆ 4247.0      ┆ 4158.0      ┆ 2024_22_KC_ ┆ … ┆ 22         ┆ 40         ┆ 18     ┆ 62    │
│         ┆             ┆             ┆ PHI         ┆   ┆            ┆            ┆        ┆       │
│ 4247.0  ┆ 4247.0      ┆ 4158.0      ┆ 2024_22_KC_ ┆ … ┆ 22         ┆ 40         ┆ 18     ┆ 62    │
│         ┆             ┆             ┆ PHI         ┆   ┆            ┆            ┆        ┆       │
└─────────┴─────────────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────┴───────┘

In [27]:
#cuantas yardas permite el equipo defensivo por cuarto
import polars as pl
#penalty_team y penalty_yards
(pbp
    .filter(pl.col("defteam").is_not_null())
    .group_by("defteam", "qtr", "season").agg(
        pl.col("yards_gained").sum(),
        pl.when(pl.col("penalty_team") == pl.col("defteam"))
            .then(pl.col("penalty_yards"))
            .otherwise(0)
            .sum()
    ).sort(["defteam", "season", "qtr"], descending=[False, False, False]))

shape: (3_849, 5)
┌─────────┬─────┬────────┬──────────────┬───────────────┐
│ defteam ┆ qtr ┆ season ┆ yards_gained ┆ penalty_yards │
│ ---     ┆ --- ┆ ---    ┆ ---          ┆ ---           │
│ str     ┆ f64 ┆ i32    ┆ f64          ┆ f64           │
╞═════════╪═════╪════════╪══════════════╪═══════════════╡
│ ARI     ┆ 1.0 ┆ 1999   ┆ 1472.0       ┆ 71.0          │
│ ARI     ┆ 2.0 ┆ 1999   ┆ 1423.0       ┆ 50.0          │
│ ARI     ┆ 3.0 ┆ 1999   ┆ 1018.0       ┆ 65.0          │
│ ARI     ┆ 4.0 ┆ 1999   ┆ 1509.0       ┆ 64.0          │
│ ARI     ┆ 1.0 ┆ 2000   ┆ 1407.0       ┆ 43.0          │
│ …       ┆ …   ┆ …      ┆ …            ┆ …             │
│ WAS     ┆ 5.0 ┆ 2023   ┆ 34.0         ┆ 0.0           │
│ WAS     ┆ 1.0 ┆ 2024   ┆ 1626.0       ┆ 93.0          │
│ WAS     ┆ 2.0 ┆ 2024   ┆ 1682.0       ┆ 110.0         │
│ WAS     ┆ 3.0 ┆ 2024   ┆ 1481.0       ┆ 179.0         │
│ WAS     ┆ 4.0 ┆ 2024   ┆ 2035.0       ┆ 212.0         │
└─────────┴─────┴────────┴──────────────┴───────────────┘

In [ ]:
import matplotlib.pyplot as plt
just_plays = pbp.filter((pl.col("play_type") != "no_play") & (pl.col("play_type") != ''))
# play_types = just_plays["play_type"].unique()
# seasons = [i for i in range(1999, 2025)]
# play_types_count = pbp.drop_nulls("play_type").group_by("play_type", "season").len()
# for play_type in play_types: 
#     fig, ax = plt.subplots()
#     ax.bar(seasons, play_types_count.filter(pl.col("play_type")==play_type)["len"])
#     ax.set_title(f"Evolucion de estilo de jugada {play_type}")
#     fig.show()

['qb_spike',
 'kickoff',
 'run',
 'field_goal',
 'extra_point',
 'qb_kneel',
 'pass',
 'punt']